name: contador

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_vite:
    runs-on: ubuntu-latest

    steps:
      - name: Download Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Dependencies
        working-directory: clase18/contador
        run: npm install

      - name: Run Vite Build
        working-directory: clase18/contador
        run: npx vite build

      - name: Guardar Zip
        uses: actions/upload-artifact@v4
        with:
          name: contador
          path: clase18/contador/dist